# 服务基本配置
server:
  runMode: debug
  port: 8000
  jwtSecret: MARKET.MONITOR.SECRET
  jwtExpire: 24   # 单位: 小时

log:
  logPath: logs/

database:
  dbType: mysql
  dbName: gateway
  user: root
  password: 980926
  host: 127.0.0.1
  port: 3306
  debug: true
  maxIdleConns: 10
  maxOpenConns: 100

redis:
  host: 127.0.0.1
  port: 6379
  maxIdle: 30
  maxActive: 30
  idleTimeout: 200

cluster:
  ip: 127.0.0.1
  port: 8880
  sslPort: 4880

http:
  addr: :9999
  readTimeout: 10
  WriteTimeout: 10
  maxHeaderBytes: 20

https:
  addr: :4433
  readTimeout: 10
  WriteTimeout: 10
  maxHeaderBytes: 20